# lib/parse.sh — materialize a per-test "record file" from tests.yaml.
# Requires: lib/common.sh sourced first.
#
# parse_test <test_id> <tests.yaml>
#   Produces ${RESULTS_DIR}/<id>.rec — a bash file that, when sourced, defines:
#
#     TEST_ID                 # e.g. 5.1a
#     TEST_SECTION            # e.g. 5.1
#     TEST_NAME               # human-readable description
#     TEST_SCRIPT             # e.g. test/job_submission/SA-Pseudo.sh (rel. to PennPRS_path)
#     TEST_SUBMISSION_ID      # unique submissionID used by PennPRS
#     TEST_ARGS=(...)         # positional args passed to the script
#     SLURM_TIME              # e.g. "02:00:00"
#     SLURM_NODES             # e.g. 1
#     SLURM_NTASKS            # e.g. 1
#     SLURM_CPUS              # e.g. 5
#     SLURM_MEM_PER_CPU       # e.g. 1000M
#     SLURM_PARTITION         # e.g. cpu
#     SLURM_QOS               # e.g. normal
#     EXPECT_BASE             # base dir to search for output folder (training tests)
#     EXPECT_MIN_WEIGHT_FILES # integer
#     EXPECT_WEIGHT_GLOB      # e.g. "*.txt"
#     EXPECT_DIR              # fixed output dir (evaluation test)
#     EXPECT_REQUIRED_FILE    # e.g. evaluation_results.txt
#
#   Also exports every `globals:` entry (PennPRS_path, homedir, ...) so the
#   record can reference them via ${...}.

parse_test() {
    local id="$1" yaml="$2"
    local rec="${RESULTS_DIR}/${id}.rec"

    # 1) Globals → exported variables -------------------------------------
    local -a global_keys
    mapfile -t global_keys < <(yq_q '.globals | keys | .[]' "$yaml" \
        | grep -v '^slurm$')
    local k v
    for k in "${global_keys[@]}"; do
        v="$(yq_q ".globals.${k}" "$yaml")"
        # Expand after all globals are set — we'll re-walk for that.
        export "${k}=${v}"
    done
    # Second pass: expand self-references (${homedir} references ${PennPRS_path}).
    for k in "${global_keys[@]}"; do
        export "${k}=$(expand_vars "${!k}")"
    done
    # Default slurm block.
    SLURM_PARTITION="$(yq_q '.globals.slurm.partition' "$yaml")"
    SLURM_QOS="$(yq_q '.globals.slurm.qos' "$yaml")"
    SLURM_NODES="$(yq_q '.globals.slurm.nodes' "$yaml")"
    SLURM_NTASKS="$(yq_q '.globals.slurm.ntasks' "$yaml")"
    [[ "$SLURM_NODES"  == "null" || -z "$SLURM_NODES"  ]] && SLURM_NODES=1
    [[ "$SLURM_NTASKS" == "null" || -z "$SLURM_NTASKS" ]] && SLURM_NTASKS=1

    # 2) Locate the test index in .tests[] --------------------------------
    local idx
    idx="$(yq_q ".tests | map(.id == \"${id}\") | index(true)" "$yaml")"
    [[ -z "$idx" || "$idx" == "null" ]] && die "Test id not found in ${yaml}: ${id}"
    local t=".tests[${idx}]"

    local name section script sid
    name="$(yq_q     "${t}.name"           "$yaml")"
    section="$(yq_q  "${t}.section"        "$yaml")"
    script="$(yq_q   "${t}.script"         "$yaml")"
    sid="$(yq_q      "${t}.submissionID"   "$yaml")"

    # 3) Args → expanded bash array --------------------------------------
    local -a args=()
    local n_args
    n_args="$(yq_q "${t}.args | length" "$yaml")"
    local i
    for ((i=0; i<n_args; i++)); do
        args+=("$(expand_vars "$(yq_q "${t}.args[${i}]" "$yaml")")")
    done

    # 4) SLURM overrides --------------------------------------------------
    local s_time s_cpus s_mem
    s_time="$(yq_q "${t}.slurm.time"         "$yaml")"
    s_cpus="$(yq_q "${t}.slurm.cpus"         "$yaml")"
    s_mem="$(yq_q  "${t}.slurm.mem_per_cpu"  "$yaml")"

    # 5) expect block -----------------------------------------------------
    local has_base has_dir
    has_base="$(yq_q "${t}.expect.base // \"\"" "$yaml")"
    has_dir="$(yq_q  "${t}.expect.dir  // \"\"" "$yaml")"

    local exp_base exp_min_w exp_w_glob
    local exp_dir exp_req_file

    if [[ -n "$has_base" && "$has_base" != "null" ]]; then
        exp_base="$(expand_vars "$has_base")"
        exp_min_w="$(yq_q "${t}.expect.min_weight_files" "$yaml")"
        exp_w_glob="$(yq_q "${t}.expect.weight_glob" "$yaml")"
    else
        exp_dir="$(expand_vars "$has_dir")"
        exp_req_file="$(yq_q "${t}.expect.required_file" "$yaml")"
    fi

    # 6) Emit record file --------------------------------------------------
    {
        printf '# Auto-generated by parse_test; do not edit by hand.\n'
        printf '# Source this file to populate TEST_* and SLURM_* variables.\n\n'
        printf 'TEST_ID=%q\n'            "$id"
        printf 'TEST_SECTION=%q\n'       "$section"
        printf 'TEST_NAME=%q\n'          "$name"
        printf 'TEST_SCRIPT=%q\n'        "$script"
        printf 'TEST_SUBMISSION_ID=%q\n' "$sid"
        # Re-export globals that args reference.
        for k in "${global_keys[@]}"; do
            printf '%s=%q\n' "$k" "${!k}"
        done
        # Args array.
        printf 'TEST_ARGS=('
        local a; for a in "${args[@]}"; do printf ' %q' "$a"; done
        printf ' )\n'
        # Slurm.
        printf 'SLURM_TIME=%q\n'         "$s_time"
        printf 'SLURM_NODES=%q\n'        "$SLURM_NODES"
        printf 'SLURM_NTASKS=%q\n'       "$SLURM_NTASKS"
        printf 'SLURM_CPUS=%q\n'         "$s_cpus"
        printf 'SLURM_MEM_PER_CPU=%q\n'  "$s_mem"
        printf 'SLURM_PARTITION=%q\n'    "$SLURM_PARTITION"
        printf 'SLURM_QOS=%q\n'          "$SLURM_QOS"
        # Expect block.
        if [[ -n "${exp_base:-}" ]]; then
            printf 'EXPECT_BASE=%q\n'            "$exp_base"
            printf 'EXPECT_MIN_WEIGHT_FILES=%q\n' "$exp_min_w"
            printf 'EXPECT_WEIGHT_GLOB=%q\n'      "$exp_w_glob"
        else
            printf 'EXPECT_DIR=%q\n'             "$exp_dir"
            printf 'EXPECT_REQUIRED_FILE=%q\n'   "$exp_req_file"
        fi
    } > "$rec"
}

# list_test_ids <tests.yaml>  — prints every `tests[].id` on its own line.
list_test_ids() {
    local yaml="$1"
    yq_q '.tests[].id' "$yaml"
}
